In [1]:
l1 = [1,2,5,6,8,9]
l2 = [3,5,8,9,0,6]

In [ ]:
l1+l2

[1, 2, 5, 6, 8, 9, 3, 5, 8, 9, 0, 6]

In [2]:
sum_l = []
for i,j in zip(l1,l2):
  sum_l.append(i+j)
print(sum_l)


[4, 7, 13, 15, 8, 15]


In [ ]:
l2 = []
for i in l1:
  l2.append(i+10)
l2

[11, 12, 15, 16, 18, 19]

In [3]:
import numpy as np

In [4]:
my_list= [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
l1 = [1,2,5,6,8,9]
l2 = [3,5,8,9,0,6]
arr1 = np.array(l1)
arr2 = np.array(l2)

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1+arr2

array([ 4,  7, 13, 15,  8, 15])

In [ ]:
arr1+10

array([11, 12, 15, 16, 18, 19])

In [8]:
arr1.ndim #dimension of an array

1

In [9]:
arr1.shape

(6,)

In [ ]:
arr1.dtype

dtype('int64')

In [10]:
arr3 = np.array([1,3.4,6,8,'a'])

In [13]:
arr3

array(['1', '3.4', '6', '8', 'a'], dtype='<U32')

In [ ]:
#Arrays are homogeneous

In [14]:
arr4 = np.array([[1,2,3],[4,6,7],[2,8,9]])

In [15]:
arr4

array([[1, 2, 3],
       [4, 6, 7],
       [2, 8, 9]])

In [16]:
arr4.shape

(3, 3)

In [17]:
arr4.size

9

In [18]:
arr4.ndim

2

In [20]:
print(list(range(5,10)))

[5, 6, 7, 8, 9]


In [19]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arr5 = np.arange(10,100,10)

In [23]:
arr5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
arr5.size

9

In [26]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [27]:
arr6 = np.arange(3,21)

In [30]:
arr6

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [32]:
arr6.reshape(9,2)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [33]:
arr6.reshape(6,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr6.reshape(9,2)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [ ]:
# arr6.reshape(3,3)

In [ ]:
arr6 = arr6.reshape(6,3)

In [ ]:
arr6

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr5=np.arange(3,21)
arr5

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
arr5 = arr5.reshape(6,3)

In [ ]:
arr5

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [34]:
import numpy as np

In [35]:
L = range(1000)
%timeit nums = [i**2 for i in L]

81.2 µs ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
nums = np.arange(1000)
%timeit nums**2

1.53 µs ± 411 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [38]:
x = np.ones((3, 2))

In [39]:
x.dtype

dtype('float64')

In [41]:
print(np.sum(nums))
print(np.mean(nums))
print(np.std(nums))
print(np.var(nums))

499500
499.5
288.6749902572095
83333.25


In [43]:
# nums

In [46]:
x = np.arange(1,100)
my_var = np.sum((x-np.mean(x))**2)/x.size
print(my_var)
print(np.var(x))

816.6666666666666
816.6666666666666


In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
z = np.diag([1,2,3,4])

In [52]:
np.diag(z)

array([1, 2, 3, 4])

In [54]:
d = np.random.random(3)
print(d)

[0.73465641 0.20400966 0.84360468]


In [ ]:
np.random.randn(4)

array([-0.1502189 ,  1.80556845,  0.8882636 , -0.72091024])

In [57]:
np.random.randint(0, 5, 8)

array([0, 3, 3, 2, 4, 1, 1, 2])

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.dtype

dtype('int64')

In [55]:
a = np.arange(10, dtype=np.float64)

In [56]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
np.array([1+3j]).dtype

dtype('complex128')

In [60]:
np.array([True, False, True]).dtype

dtype('bool')

In [61]:
np.array(["Ram", "Hello"])

array(['Ram', 'Hello'], dtype='<U5')

In [62]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[3]=10

In [64]:
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9])

In [65]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [72]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a[1::2][::-1][::-1]

array([1, 3, 5, 7, 9])

In [73]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [74]:
np.shares_memory(a, b)

True

In [75]:
c = a[::2].copy()

In [76]:
np.shares_memory(a, c)

False

In [77]:
a = np.zeros((4, 4))
b = np.ones((4, 4))
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [78]:
c = np.vstack((a, b))
c.shape

(8, 4)

In [82]:
d = np.hstack((a, b))
d.shape
d

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [80]:
np.concatenate([a,b], axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
array1 = np.array([1,2,3])

In [ ]:
array1.shape

(3,)

In [84]:
d.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
a = np.arange(4)
b = a.T
np.dot(a, b)

np.int64(14)

In [86]:
import pandas as pd

In [87]:
weather_data = [("1/1/2024", 32, 6, "Rain"),
                ("2/11/2024", 35, 7, "Sunny")]

In [88]:
df = pd.DataFrame(weather_data,columns=["date", "temperature", "wind" ,"climate"])

In [89]:
df

date  temperature  wind climate
0   1/1/2024           32     6    Rain
1  2/11/2024           35     7   Sunny

In [90]:
import pandas as pd
df = pd.read_csv("auto-mpg.csv")

In [94]:
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [96]:
df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [97]:
df.shape

(398, 9)

In [99]:
df[["mpg", "weight"]]

mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
393  27.0    2790
394  44.0    2130
395  32.0    2295
396  28.0    2625
397  31.0    2720

[398 rows x 2 columns]

In [101]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [ ]:
df.shape

(398, 9)

In [ ]:
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [ ]:

df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [102]:
df[["mpg", "car name"]]

mpg                   car name
0    18.0  chevrolet chevelle malibu
1    15.0          buick skylark 320
2    18.0         plymouth satellite
3    16.0              amc rebel sst
4    17.0                ford torino
..    ...                        ...
393  27.0            ford mustang gl
394  44.0                  vw pickup
395  32.0              dodge rampage
396  28.0                ford ranger
397  31.0                 chevy s-10

[398 rows x 2 columns]

In [103]:
print(df["mpg"].min())
print(df["mpg"].max())
print(df["mpg"].mean())
print(df["mpg"].std())
print(df["mpg"].var())

9.0
46.6
23.514572864321607
7.815984312565782
61.089610774274405


In [104]:
print(df["weight"].min())

1613


In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [106]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [112]:
df[df["weight"]==df["weight"].min()]["car name"]

54    datsun 1200
Name: car name, dtype: object

In [115]:
df[df["mpg"]==df["mpg"].max()][["mpg", "car name"]]

mpg   car name
322  46.6  mazda glc

In [116]:
df[df["mpg"]==df["mpg"].min()]["car name"]

28    hi 1200d
Name: car name, dtype: object

In [119]:
df[df["mpg"]>40]["car name"]

244    volkswagen rabbit custom diesel
309                          vw rabbit
322                          mazda glc
324                         datsun 210
325               vw rabbit c (diesel)
326                 vw dasher (diesel)
329                honda civic 1500 gl
330               renault lecar deluxe
394                          vw pickup
Name: car name, dtype: object

In [ ]:
df[df.mpg == df["mpg"].min()]["car name"]

28    hi 1200d
Name: car name, dtype: object

In [120]:
df[["car name", "weight"]]

car name  weight
0    chevrolet chevelle malibu    3504
1            buick skylark 320    3693
2           plymouth satellite    3436
3                amc rebel sst    3433
4                  ford torino    3449
..                         ...     ...
393            ford mustang gl    2790
394                  vw pickup    2130
395              dodge rampage    2295
396                ford ranger    2625
397                 chevy s-10    2720

[398 rows x 2 columns]

In [121]:
new_df = df[["car name", "weight"]]
new_df.to_csv("new_df.csv")

In [ ]:
new_df = df[["car name", "weight"]]
new_df_2 = df[["weight", "car name"]]

In [ ]:
new_df.head(1)

car name  weight
0  chevrolet chevelle malibu    3504

In [ ]:
new_df_2.head(1)

weight                   car name
0    3504  chevrolet chevelle malibu

In [122]:
new_df.to_excel("output.xlsx", sheet_name="sheet1")

In [ ]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [124]:
df["mpg_weight"] = df["mpg"]*df["weight"]

In [126]:
df.to_csv("auto-mpg.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [127]:
g = df.groupby("model year")

In [ ]:
df.shape

(398, 9)

In [ ]:
# df_sample = df.sample(frac=0.2)

In [ ]:
# df_sample.shape

(80, 9)

In [128]:
g = df.groupby("model year")

In [129]:
print(g)

In [130]:
g.max()

mpg  cylinders  displacement horsepower  weight  acceleration  \
model year                                                                   
70          27.0          8         455.0         97    4732          20.5   
71          35.0          8         400.0          ?    5140          20.5   
72          28.0          8         429.0         97    4633          23.5   
73          29.0          8         455.0         95    4997          21.0   
74          32.0          8         350.0          ?    4699          21.0   
75          33.0          8         400.0         98    4668          21.0   
76          33.0          8         351.0         95    4380          22.2   
77          36.0          8         400.0         98    4335          19.0   
78          43.1          8         318.0         97    4080          21.5   
79          37.3          8         360.0         90    4360          24.8   
80          46.6          6         225.0          ?    3381          23.7   
81          39.1          8         350.0          ?    3725          20.7   
82          44.0          6         262.0          ?    3035          24.6   

            origin                      car name  mpg_weight  
model year                                                    
70               3  volkswagen 1131 deluxe sedan     66800.0  
71               3          volkswagen model 111     66820.0  
72               3               volvo 145e (sw)     64064.0  
73               3                   volvo 144ea     68448.0  
74               3             volkswagen dasher     66256.0  
75               3                   volvo 244dl     74688.0  
76               3                     vw rabbit     73766.0  
77               3      volkswagen rabbit custom     70252.5  
78               3                   volvo 264gl     85553.5  
79               3              vw rabbit custom     89700.0  
80               3          vw rabbit c (diesel)    107380.0  
81               3                  volvo diesel     99085.0  
82               3                     vw pickup    114570.0

In [132]:
# for x, model_df in g:
#   print(x)
#   print(model_df)

In [ ]:
df.describe()

In [133]:
us_weather = pd.DataFrame({
    "city": ["newyork", "chicago", "seatle"],
    "temperature": [21, 14, 35],
    "humidity": [68, 65, 75],
})

In [134]:
us_weather

city  temperature  humidity
0  newyork           21        68
1  chicago           14        65
2   seatle           35        75

In [135]:
india_weather = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 21, 35],
    "humidity": [60, 75, 78],
})

In [136]:
india_weather

city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78

In [137]:
weather_us_india = pd.concat([india_weather, us_weather],\
                             ignore_index=True)

In [138]:
weather_us_india

city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78
3   newyork           21        68
4   chicago           14        65
5    seatle           35        75

In [ ]:
weather_us_india["temperature"]<30

In [ ]:
weather_us_india[weather_us_india["temperature"]<30]

In [ ]:
pd.concat([us_weather, india_weather], axis=1)

In [ ]:
pd.merge(india_weather, us_weather, on="temperature")

In [141]:
df = pd.DataFrame([1, 2, 3, 4], index = [49, 48, 12, 3])

In [142]:
df

0
49  1
48  2
12  3
3   4

In [143]:
df.loc[49]

0    1
Name: 49, dtype: int64

In [145]:
df.iloc[2:4]

0
12  3
3   4

In [146]:
city1 = pd.Series([12, -6, 8, -3], index = ["day1", "day2", "day3", "day4"])

In [147]:
city1

day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [148]:
city1[city1>2]

day1    12
day3     8
dtype: int64

In [149]:
# city1.isna()
city1[~city1.isna()]

day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [ ]:
city1*3

In [151]:
df = pd.read_csv("auto-mpg.csv")

In [152]:
df["cylinders"].unique()

array([8, 4, 6, 3, 5])

In [153]:
df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [154]:
df.values

array([[0, 18.0, 8, ..., 1, 'chevrolet chevelle malibu', 63072.0],
       [1, 15.0, 8, ..., 1, 'buick skylark 320', 55395.0],
       [2, 18.0, 8, ..., 1, 'plymouth satellite', 61848.0],
       ...,
       [395, 32.0, 4, ..., 1, 'dodge rampage', 73440.0],
       [396, 28.0, 4, ..., 1, 'ford ranger', 73500.0],
       [397, 31.0, 4, ..., 1, 'chevy s-10', 84320.0]], dtype=object)

In [155]:
car_new = df.drop(["origin", "car name"], axis= 1)

In [157]:
car_new.head(2)

Unnamed: 0   mpg  cylinders  displacement horsepower  weight  acceleration  \
0           0  18.0          8         307.0        130    3504          12.0   
1           1  15.0          8         350.0        165    3693          11.5   

   model year  mpg_weight  
0          70     63072.0  
1          70     55395.0