In [13]:
a = range(1000000)
b = range(1000000)
arr_a = np.array(a)
arr_b = np.array(b)

In [14]:
import time
import numpy as np

In [15]:
start = time.time()
c = []
for x,y in zip(a,b):
  su = x+y
  c.append(su)
end = time.time()
print('total time taken:' , (end-start)*1000)

total time taken: 223.6950397491455


In [16]:
start = time.time()
arr_c = arr_a + arr_b
end = time.time()
print('total time taken: ', (end-start)*1000)

total time taken:  2.562284469604492


In [17]:
type(arr_c)

numpy.ndarray

In [ ]:
# list and array

#list can store multiple datatypes
# array can store only single datatype

In [18]:
a = np.array([1,2,3,4,5])

In [19]:
a.ndim #to get the dimension of array

1

In [20]:
a.shape

(5,)

In [21]:
a.dtype #to get the datatype

dtype('int64')

In [23]:
arr2 = np.array([[1,3,5,7],[2,4,6,8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr2.dtype

dtype('int64')

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
print(list(range(1,11)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr3 = np.arange(5,21)
print(arr3)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [29]:
arr3.reshape(4,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [30]:
arr3.reshape(2,8)

array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20]])

In [31]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [32]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr[7]

7

In [34]:
arr = np.array([4,1,9,3,7,3,2])

In [35]:
print(arr)

[4 1 9 3 7 3 2]


In [36]:
arr[0]

4

In [37]:
arr[:3]

array([4, 1, 9])

In [ ]:
arr[4:]

array([7, 3, 2])

In [ ]:
print(arr)

[4 1 9 3 7 3 2]


In [ ]:
arr[2,4,6]

IndexError: ignored

In [ ]:
arr[[2,4,6]]

array([9, 7, 2])

In [38]:
arr2 = np.array([[-7,5,-2,4],[5,2,7,3],[10,-13,-3,5]])

In [39]:
print(arr2)

[[ -7   5  -2   4]
 [  5   2   7   3]
 [ 10 -13  -3   5]]


In [ ]:
# 3 5
# 5 10

In [45]:
arr2[1:,1:3]

array([[  2,   7],
       [-13,  -3]])

In [40]:
arr2.shape

(3, 4)

In [41]:
arr2[2]

array([ 10, -13,  -3,   5])

In [42]:
arr2[1,2]

7

In [ ]:
arr2[[1,2]]

array([[  5,   2,   7,   3],
       [ 10, -13,  -3,   5]])

In [43]:
arr2[:,1] # second columnn

array([  5,   2, -13])

In [46]:
arr3 = np.arange(10,82,2)
print(arr3)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80]


In [47]:
len(arr3)

36

In [48]:
arr3 = np.arange(10,82,2).reshape(6,6)
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [49]:
# if you want to view the columns of index 0 and 3
arr3[:,[0,3]]

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [50]:
# to view the first 2 rows
arr3[:2,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [51]:
# mathematical operations
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [52]:
# to get sum of all values
arr3.sum()

1620

In [53]:
np.sum(arr3)

1620

In [54]:
1620/36


45.0

In [55]:
np.mean(arr3)

45.0

In [56]:
arr3.mean()

45.0

In [61]:
arr3 = arr3.reshape(12,3)

In [62]:
arr3

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38],
       [40, 42, 44],
       [46, 48, 50],
       [52, 54, 56],
       [58, 60, 62],
       [64, 66, 68],
       [70, 72, 74],
       [76, 78, 80]])

In [66]:
arr3.mean(axis = 1)

array([12., 18., 24., 30., 36., 42., 48., 54., 60., 66., 72., 78.])

In [67]:
np.mean(arr3)

45.0

In [ ]:
10+ 12+ 14+ 16+ 18+ 20

90

In [ ]:
90/6


15.0

In [ ]:
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [64]:
arr3+4

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54],
       [56, 58, 60],
       [62, 64, 66],
       [68, 70, 72],
       [74, 76, 78],
       [80, 82, 84]])

In [ ]:
arr3*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [ ]:
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [ ]:
arr3[5]= -9
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [-9 -9 -9 -9 -9 -9]]


In [69]:
x_abs = np.abs(arr3)
x_mean = np.mean(arr3)
x_std = np.std(arr3)
x_var = np.var(arr3)
x_min = np.min(arr3)
x_max = np.max(arr3)
x_sum = np.sum(arr3)
x_q1 = np.quantile(arr3,0.25)
x_q3 = np.quantile(arr3,0.75)
x_median = np.median(arr3)
x_sq = np.square(arr3)
x_sqrt = np.sqrt(arr3)
x_log = np.log(arr3)
x_log10 = np.log10(arr3)
x_log2 = np.log2(arr3)
x_p25 = np.percentile(arr3,25)


In [ ]:
# special arrays

In [ ]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)

In [76]:
C = A.dot(B)

In [77]:
print(C)

[[28 34]
 [76 98]]


In [78]:
C.T # to get the transpose of a matrix

array([[28, 76],
       [34, 98]])

In [79]:
np.dot(C,C.T) # multiplication of a matrix and its transpose

array([[ 1940,  5460],
       [ 5460, 15380]])

In [ ]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
np.vstack((a,b)) #for vertical stacking

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [ ]:
np.concatenate((a,b))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.concatenate([a,b], axis =1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [ ]:
# ravel and flatten
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [-9 -9 -9 -9 -9 -9]]


In [ ]:
arr3.shape

(6, 6)

In [ ]:
f = arr3.flatten()
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 -9 -9 -9 -9 -9 -9]


In [ ]:
f.shape

(36,)

In [ ]:
r = arr3.ravel()
print(r)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 -9 -9 -9 -9 -9 -9]


In [ ]:
r.shape

(36,)

In [ ]:
# Random
np.random.randint(1,10, 2)

array([6, 3])

In [ ]:
arr_h

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
np.random.shuffle(arr_h)
arr_h

array([1.89, 1.79, 1.68, 1.73, 1.71])